### ISSUE TITLE
8.7 Manual Test Plan

### ISSUE THREAD

**Issue by lahsivjar** [elastic/apm-server#10200]
# Manual Test Plan

When picking up a test case, please add your name to this overview beforehand and tick the checkbox when finished.
Testing can be started when the first build candidate (BC) is available in the CFT region.

## Smoke Testing ESS setup

Thanks to https://github.com/elastic/apm-server/issues/8303 further smoke tests are run automatically on ESS now.
**Consider extending the smoke tests to include more test cases which we'd like to cover**

## Go agent

- [x] https://github.com/elastic/apm-agent-go/pull/1364 @kruskall 
- [x] https://github.com/elastic/apm-agent-go/pull/1336 @marclop 
- [x] https://github.com/elastic/apm-agent-go/issues/1355
- [x] https://github.com/elastic/apm-agent-go/pull/1339 @marclop

## Lambda extension

Outside 8.7 release scope for this iteration.

## APM Kubernetes Attacher

No relevant code changes.

## Test cases from the GitHub board

- [x] [apm-server 8.7 test-plan](https://github.com/elastic/apm-server/issues?q=is%3Aissue%7Cpr+label%3Atest-plan+-label%3Atest-plan-ok+is%3Aclosed+label%3Av8.7.0)

Add yourself as _assignee_ on the PR before you start testing.

## Regressions

- [x] #10056
  - [x] Resolved by #10297
- [x] #10061
  - [x] Resolved by #10302
- [x] #9722
  - [x] Resolved by #10367
