### ISSUE TITLE
8.8 Manual Test Plan

### ISSUE THREAD

**Issue by carsonip** [elastic/apm-server#10700]
# Manual Test Plan

When picking up a test case, please add your name to this overview beforehand and tick the checkbox when finished.
Testing can be started when the first build candidate (BC) is available in the CFT region.

## Smoke Testing ESS setup

Thanks to https://github.com/elastic/apm-server/issues/8303 further smoke tests are run automatically on ESS now.
**Consider extending the smoke tests to include more test cases which we'd like to cover**

## Go agent

- [x] https://github.com/elastic/apm-agent-go/pull/1407
- [x] https://github.com/elastic/apm-agent-go/pull/1410

## Lambda extension

- [x] https://github.com/elastic/apm-aws-lambda/pull/384

## APM Kubernetes Attacher

No changes

## Test cases from the GitHub board

- [x] [apm-server 8.8 test-plan](https://github.com/elastic/apm-server/issues?q=is%3Apr+label%3Atest-plan+-label%3Atest-plan-ok+is%3Aclosed+label%3Av8.8.0)

Add yourself as _assignee_ on the PR before you start testing.

## Regressions

Link any regressions to this issue.

**Comment by axw** [comment]
I think we can mark https://github.com/elastic/apm-aws-lambda/pull/384 as tested, based on https://github.com/elastic/apm-aws-lambda/pull/384#pullrequestreview-1390825211?

**Comment by carsonip** [comment]
> I think we can mark [elastic/apm-aws-lambda#384](https://github.com/elastic/apm-aws-lambda/pull/384) as tested, based on [elastic/apm-aws-lambda#384 (review)](https://github.com/elastic/apm-aws-lambda/pull/384#pullrequestreview-1390825211)?

Sounds good to me!

**Comment by simitt** [comment]
Assigned people to the testing issues - please test as quickly as possible, latest end of this week. The new BC-3 is going to be triggered next week.

**Comment by simitt** [comment]
@carsonip can this be closed now?
