### ISSUE TITLE
Edit APM docs

### ISSUE THREAD

**Issue by dedemorton** [elastic/apm-server#1090]
The APM documentation needs a thorough technical edit to fix duplication and clean up the wording.

Content that requires extra attention:

- [x] Tuning topics - Addressed in #1530, #1576
- [x] Content (added in https://github.com/elastic/apm-server/pull/1088)  - Addressed in #1530, #1576
- [x] Performance tuning docs (added in https://github.com/elastic/apm-agent-nodejs/pull/419) Addressed in elastic/apm-agent-nodejs/pull/635, elastic/apm-agent-nodejs/pull/665
