### ISSUE TITLE
8.9 manual test plan 

### ISSUE THREAD

**Issue by kruskall** [elastic/apm-server#11039]
# Manual Test Plan

When picking up a test case, please add your name to this overview beforehand and tick the checkbox when finished.
Testing can be started when the first build candidate (BC) is available in the CFT region.

## Smoke Testing ESS setup

Thanks to https://github.com/elastic/apm-server/issues/8303 further smoke tests are run automatically on ESS now.
**Consider extending the smoke tests to include more test cases which we'd like to cover**

## Go agent

```[tasklist]
### Tasks
- [ ] https://github.com/elastic/apm-agent-go/pull/1424
- [ ] https://github.com/elastic/apm-agent-go/pull/1437
- [ ] https://github.com/elastic/apm-agent-go/pull/1438
- [ ] https://github.com/elastic/apm-agent-go/pull/1441
- [ ] https://github.com/elastic/apm-agent-go/pull/1472
```

## Lambda extension

```[tasklist]
### Tasks
- [ ] https://github.com/elastic/apm-aws-lambda/pull/392
```

## APM Kubernetes Attacher

nil

## Test cases from the GitHub board

```[tasklist]
### Tasks
- [ ] [apm-server 8.9 test-plan](https://github.com/elastic/apm-server/issues?q=is%3Apr+label%3Atest-plan+-label%3Atest-plan-ok+is%3Aclosed+label%3Av8.9.0)
- [ ] https://github.com/elastic/apm-server/issues/11049
```

Add yourself as _assignee_ on the PR before you start testing.

## Regressions

Link any regressions to this issue.

**Comment by kruskall** [comment]
I opened a separate issue for the protobuf changes as it wasn't ideal to add every single PR to the test plan

**Comment by simitt** [comment]
Is the testing finished and can this be closed?

**Comment by simitt** [comment]
pinging @kruskall for a status update and closing this out when everything is done

**Comment by kruskall** [comment]
Sorry for the late status update. I think this can be closed.
