### ISSUE TITLE
Intake v2 support

### ISSUE THREAD

**Issue by roncohen** [elastic/apm-server#1237]
This is an issue to track intake v2 support in the APM Server

**Blockers:**

- [x] https://github.com/elastic/apm-server/pull/1137 Refactor processors
- [x] https://github.com/elastic/apm-server/pull/1141 Separate span
- [x] https://github.com/elastic/apm-server/pull/1239 Refactor payloads
- [x] https://github.com/elastic/apm-server/issues/1238, Implementation of elementary v2 functionality, including:
   * v2 endpoints
  * processing of ndjson objects
  * allowing spans to be sent separatly
  * add `timestamp` and `transaction.id` to spans
  * allow for same compression methods as v1
  * allow for `transactions, spans, errors, metadata`
- [x] https://github.com/elastic/apm-server/pull/1353 Set the right content type
- [x] https://github.com/elastic/apm-server/issues/1236 Create a summary response for Intake V2
- [x] https://github.com/elastic/apm-server/pull/1324 Move non-web related processing into processor, add "publish" package 
- [x] Add server-level integration tests to test endpoints
- [x] Add  integration tests for various errors
- [x] https://github.com/elastic/apm-server/issues/1240 Handling errors in Intake V2 
- [x] https://github.com/elastic/apm-server/issues/1241 How to handle partial transactions
- [x] https://github.com/elastic/apm-server/issues/1242 How to handle spans starting after transaction is already finished.
- [x] elastic/apm-server#1254 intake v2 client utility
- [x] https://github.com/elastic/apm-server/issues/1276 Update json spec for V2
- [x] https://github.com/elastic/apm-server/issues/1355 adapt application metrics
- [x] https://github.com/elastic/apm-server/issues/1336 design intake v2 endpoints
- [x] https://github.com/elastic/apm-server/issues/1356 rename 'metric' to 'metricset'
- [x] https://github.com/elastic/apm-server/issues/1376 Add benchmark tests
- [x] https://github.com/elastic/apm-server/pull/1384 Require `error.id` and change format.
- [x] https://github.com/elastic/apm-server/issues/1288 Finalize processor/package_tests style tests
- [x] https://github.com/elastic/apm-server/issues/1298 Investigate "full queue" behavior
- [x] https://github.com/elastic/apm-server/issues/1299 Investigate which limits/configs are useful for intake v2
- [x] Ensure common problem section is valid for both versions or specifies the version.
- [x] https://github.com/elastic/apm-server/pull/1409 follow up on  #1356, rename code symbols from "metrics" to "metricset" 
- [x] https://github.com/elastic/apm-server/issues/1340#issuecomment-424740133 v2: Require either `span.start` or `span.timestamp`

Non-blockers: 
- [ ] https://github.com/elastic/apm-server/issues/1410 Deny `null` values in JSON spec  - Postponed to 7.0
- [x] elastic/apm-server#1385 Update instrumentation
- [ ] https://github.com/elastic/apm-server/issues/1285 Investigate parallelizing decode and validate
- [ ] https://github.com/elastic/apm-server/issues/1329 Add proper documentation around v2 to APM Server docs and clarify which errors could happen in which Intake API version.
- [ ] https://github.com/elastic/apm-server/pull/1413#pullrequestreview-161369970 make sure `model/transaction/event_test.go` has a `TestEventTransform` that covers v2 events

**Comment by felixbarny** [comment]
To see all changes in the intake API, open https://github.com/elastic/apm-server/compare/v2 and search for `docs/spec/`.

**Comment by roncohen** [comment]
all blockers are resolved. Closing
