### ISSUE TITLE
Add Intake v2 related documentation

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#1329]
Add proper documentation around v2 to APM Server docs and clarify which errors could happen in which Intake API version. Ensure common problem section is valid for both versions or specifies the version.

- [x] #1484 Document intake API Changes
- [x] #1485 Document data model in ES
- [x] #1486 Documentation updates: Troubleshooting and tuning (replaced with #1537)
- [x] #1487 Create 6.4 -> 6.5 upgrade guide
- [x] #1530
- [x] #1537 Update Tuning section to show v1/v2 differences

**Comment by watson** [comment]
The [intake API docs](https://www.elastic.co/guide/en/apm/server/current/intake-api.html) should be updated as well to reflect the new endpoints. The Node.js agent currently links to these and those links need to be updated in the Node.js docs.

**Comment by roncohen** [comment]
this should include documenting new configuration options introduced for v2
