### ISSUE TITLE
docs: broken release notes links

### ISSUE THREAD

**Issue by kruskall** [elastic/apm-server#13642]
Several links to release notes are broken

```[tasklist]
### Tasks
- [x] 7.x versions (e.g. https://github.com/elastic/apm-server/releases/tag/v7.17.22)
- [x] some 8.x versions (e.g. https://github.com/elastic/apm-server/releases/tag/v8.14.0)
- [x] malformed changelog in 8.14 page: https://www.elastic.co/guide/en/observability/8.14/_added.html
- [x] inconsistency in 7.x page: APM Server vs APM (e.g. https://www.elastic.co/guide/en/apm/guide/7.17/release-notes.html and https://www.elastic.co/guide/en/apm/guide/7.17/release-notes-7.16.html)
```

**Comment by 1pkg** [comment]
Manually fixed release tags between 7.17.20 and 7.17.26, because of the page change APM Server vs APM we will have to do the same fix for the remaining 7.17 releases which shouldn't be a big trouble since only few are remaining.

Additionally manually fixed release tags for 8.14.x releases where we had a faulty pipeline version which used "main" branch as the anchor reference.

**Comment by 1pkg** [comment]
> [@1pkg](https://github.com/1pkg) I think this has been resolved. Can we close this ?

@kruskall automation will still produce broken links for the remaining 7.x releases, so I want to keep this task open to not forget to fix them manually too. It's less effort to just fix the remaining 7.x links manually and track it with this issue rather than trying to fix automation.
