### ISSUE TITLE
monitoring: apm-server not shiping tbs monitoring metrics

### ISSUE THREAD

**Issue by endorama** [elastic/apm-server#14247]
Follow up on [#13475](https://github.com/elastic/apm-server/issues/13475)

Not all metrics have been included in the previous fixes. One of which is `beat.stats.apm_server.sampling.tail.*`.

```[tasklist]
### Tasks
- [ ] https://github.com/elastic/elasticsearch/pull/121543
- [ ] https://github.com/elastic/beats/pull/42569
- [ ] https://github.com/elastic/integrations/pull/12568
``` 

## How to test these PRs

See https://github.com/elastic/apm-server/issues/13475

Enable TBS, see that metrics are indexed.

**Comment by lucabelluccini** [comment]
If possible, let's also publish the value of `sampling.tail.storage_limit` and a boolean metric to tell if TBS is "bypassed" because of the `sampling.tail.storage_limit` is exceeded.

**Comment by carsonip** [comment]
> the value of sampling.tail.storage_limit as a number so we can easily plot it

Created https://github.com/elastic/apm-server/issues/15533 to track this

> a boolean metric to tell if TBS is "bypassed" because of the sampling.tail.storage_limit is exceeded (instead of relying on logs)

It doesn't have to be a boolean metric. I believe the existing `sampling.tail.events.failed_writes` should be good enough to determine this. It should be available once this issue is resolved.

**Comment by carsonip** [comment]
Closing as all PRs and backport PRs are merged. This will need a changelog line in 8.16.4 and 8.17.2: `Fix unmapped or dropped APM Server tail sampling monitoring metrics in APM Server self-monitoring, Stack monitoring, Metricbeat, and Elastic Agent integration {issue}14247[14247]`

**Comment by endorama** [comment]
Changelog PR up: https://github.com/elastic/apm-server/pull/15561
