### ISSUE TITLE
7.0.0 ECS / Field Renames for 6.x compat

### ISSUE THREAD

**Issue by graphaelli** [elastic/apm-server#1682]
Meta issue to track tasks related to ECS and field renames for 7.0.0

- ~~[ ] update apm-server writes to corresponding to 6.6 aliases elastic/apm-server#1683~~
- [ ] add/set_labels methods in agents, like add/set_tags
- [x] update included ML integration to use service.name
- [ ] update apm-integration-testing to support the changes elastic/apm-integration-testing#261
- ~~[ ] ensure dashboards work with 6.x indices #1786~~
- [x] remove visualization, dashboards and dashboard commands https://github.com/elastic/apm-server/issues/1673
- [ ] update and review documentation  https://github.com/elastic/apm-server/issues/1803
- [ ] update and review changelog https://github.com/elastic/apm-server/issues/1790

Moving fields around in APM Server:
- [x] set host.* fields from agents elastic/apm-server#1684
- [x] set agent.* fields from agents elastic/apm-server#1730
- [x] move `tags` to `labels` in APM Server https://github.com/elastic/apm-server/issues/1826
- [x] update non indexed fields elastic/apm-server#1752
- [x] docker/kubernetes fields elastic/apm-server#1651 
- [x] move `user` related fields elastic/apm-server#1782
- [x] fix user_agent pipeline to follow ECS schema https://github.com/elastic/apm-server/issues/1805
- [x] settle on non ECS field names https://github.com/elastic/apm-server/issues/1804

**Comment by graphaelli** [comment]
All fields have been moved for compliance with ECS.
The ML integration from the APM side has been updated to use `service.name` instead of `context.service.name` already.
https://github.com/elastic/apm/issues/42 is tracking the tags->labels api changes for agents

We will track the remaining doc and changelog updates part of the general 7.0 release tasks, closing this one out.
