### ISSUE TITLE
[docs][meta] APM Overview improvements

### ISSUE THREAD

**Issue by bmorelli25** [elastic/apm-server#1915]
Meta issue for tracking improvements to the APM Overview documentation:

- [x] Create a directory that links to all available APM documentation, repositories, and discuss forum (#1780)
- [x] Improve agent installation table
- [x] Format agent/server compatibility better
- [x] Move release notes to their own pages like we have in the APM Server #1940     
- [x] Change release notes to release highlights elastic/apm-server#1940
- [x] Use Elastic style (elastic/apm-dev/issues/444)
- [ ] ~Add section on observability~ To be added in the redesign
- [x] Discuss what agents do/don't do -- This was added to each Agent's overview
- [x] Use `beta[]` tag instead of "beta" (also applies to the server and Kib: https://github.com/elastic/kibana/issues/32900)

Asciidoctor tagged regions:
- [ ] ~The Overview currently links out to Kibana and Elasticsearch. Explore the idea of using custom include statements to bring documentation from other books into the Overview.~
- [ ] ~Similar to the above point, consider either moving or including the APM UI documentation in the Overview instead of linking to it.~

EDIT: APR, 2020 - We won't be doing any of the crossed items. They will be fixed in the documentation redesign.
