### ISSUE TITLE
Proxy configuration from Kibana to agents

### ISSUE THREAD

**Issue by jalvz** [elastic/apm-server#2126]
### Initial requirements

- Fetch configuration changes from a Kibana REST API
- Serve configuration to agents with an `Etag` header
- Support granularity per service name and environment
- Minimize within reason the number of requests to Kibana and the response time for agents

### Background

- It has been considered to fetch configuration directly form Elasticsearch
- It has been considered to poll Kibana for all configuration at regular intervals

### Subtasks

- [x] Main functionality https://github.com/elastic/apm-server/pull/2289
- [x] Beats support https://github.com/elastic/beats/pull/12266
- [x] Performance https://github.com/elastic/apm-server/issues/2220
- [x] Integration tests https://github.com/elastic/apm-server/issues/2219
- [x] Server Docs https://github.com/elastic/apm/issues/86

### Parent meta-issue

- https://github.com/elastic/apm/issues/4

**Comment by jalvz** [comment]
POC: https://github.com/elastic/apm-server/pull/2095
