### ISSUE TITLE
Rework beater package

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#2489]
The `beater` package deals with a couple of technical debts at the moment. This is a meta issue to discuss issues and how to address them. 

The `logging` and `monitoring` handling is spread all over the package, leading to errors and not fully logged and monitored requests (e.g. ACM requests increase counter for requests, but not for responses). 

The response writer logic needs some refactoring to have a unique and more idiomatic way of writing responses and errors. Response handling should be separated from increasing monitoring counters. 

After some research the suggested solution is to introduce a `Context` struct pool. A `Context` is passed around between `Handlers` within one request, abstracting the `http.ResponseWriter` and the `*http.Request`. For every new request the context pool takes care of reusing an idle context, and resetting it to the current request.

Introducing a `Context` allows for better separation of concerns for the single middleware handlers, while reusing structs to increase performance.  

Since this is a larger effort, the changes will be introduced in separate PRs, directed against a feature branch. Once all changes are in and all tests are accordingly adapted, the feature branch will be merged against master. 

Separating the effort into following tasks:
- [x] Introducing `Context` and centralizing `logging` (elastic/apm-server#2492 )
- [x] Centralized `monitoring` handling (elastic/apm-server#2493 )
- [x] Rework response writer logic to be more idiomatic and less error prone (elastic/apm-server#2494 )
- [x] Restructure beater package. Move handlers to middleware package and add unit tests per handler, while keeping integration tests for routes. (https://github.com/elastic/apm-server/pull/2518)
- [x] Change unintuitive abbreviations. (https://github.com/elastic/apm-server/pull/2518)
- [x] Change current log handling to get rid of additional `error` and unify used terminology (elastic/apm-server#2201 )
- [x] Introduce proper monitoring handling for ACM. Counters for responses are missing. (#2142   )
- [x] Discuss and change monitoring handling for `root` and `asset` routes. (elastic/apm-server#2142 )
