### ISSUE TITLE
Breaking changes for 8.0

### ISSUE THREAD

**Issue by graphaelli** [elastic/apm-server#2631]
Consolidated list of breaking changes we should consider for the next major.

- [ ] replace `timestamp.us` and `span.start` with @timestamp (from #1678)
- [ ] add [`date_range`](https://www.elastic.co/guide/en/elasticsearch/reference/current/range.html) field for trace events
- [ ] Revisit `error` fields and grouping logic (from #1769)
- [ ] Healthcheck improvements (from meta #2632)
- [ ] bug fixes in `beater` package that are breaking changes (TODO comments in code) 
- [ ] ensure every route only accepts dedicated _METHOD_ and put logic for it directly into the `mux.go` file when creating routes.
- [ ] start filling in `event.*` fields (not breaking)
- [ ] reject events with an empty transaction type (https://github.com/elastic/apm-server/issues/3141)
- [ ] use xxHash for grouping key calculation (https://github.com/elastic/apm-server/issues/3226)
- [ ] consider json-schema changes after separating RUM decoding, (eg: optional timestamp)
- [ ] require `transaction.name` - already happens by convention, should formalize since UI doesn't show no-name transactions
- [x] remove `page.url` and `page.referer` (https://github.com/elastic/apm-server/pull/3857)
- [ ] aligning `db` fields in ECS is potentially a breaking change for `span.db`, see [ECS#514](https://github.com/elastic/ecs/issues/514#issuecomment-663123661) 
- [ ] store some metrics as `aggregate_metric_double` https://github.com/elastic/apm-server/issues/4612
- [ ] create data stream specific ingest pipelines
- [ ] ILM policy to include delete / frozen tier
------------------------------

Discarded for 8.0:

~- [ ] Remove `null` values from Json Spec (from #1410)~
~- [ ] Add `labels` and deprecate `tags` on Intake API (from #1835)~
~- [ ] Move onboarding index to system/dot-prefix or saved object~
~- [ ] Multiple listener support (from #1405)~
~- [ ] Synchronous upload of Sourcemaps or consider to move upload endpoint to Kibana (from #2862 )~
~- [ ] move pipeline configuration into index template / use `final_pipeline`~ (Moving to Fleet.)
~- [ ] restructure apm-server.yml file to follow along with filebeat input structure [as suggested](https://github.com/elastic/apm-server/pull/2976/files#r352960036)~ (Jaeger/OTLP will be served on the same port as the Elastic APM agent protocol)

------------------------------

* Cross out rather than deleting abandoned ideas
* Check off implemented ideas
* Reopen/reuse existing issues if proceeding with that idea

**Comment by jalvz** [comment]
I won't create an issue for this, but by 8.0 we should look also into consistency responses. It seems weird that a failed auth returns  `{"error": "invalid token"}`, but wrong method returns a whole 
```
{
  "accepted": 0,
  "errors": [
    {
      "message": "only POST requests are supported"
    }
  ]
}
```
Particularly because a 405 obviously won't cause any events to be ingested

**Comment by graphaelli** [comment]
@axw posting your notes here for safe keeping.  Regarding options for moving to`date_nanos` `@timestamp`:

* `@timestamp` as `date_nanos` with a default format of `epoch_millis` and a runtime field for `<foo>.timestamp.us` until we can move fully onto `@timestamp`.
* UI uses the fields API to query `@timestamp` with format `strict_date_optional_time_nanos`, and also queries `<foo>.timestamp.us` and uses that if it exists. We would stop mapping and indexing the latter, this would just be for backwards compatibility

**Comment by axw** [comment]
For discussion, some things I'd like to look at for 8.0:

- remove index template, ILM policy, pipeline setup & related config -- move all setup to integration package
- remove old index selector support, always create data streams (https://github.com/elastic/apm-server/issues/5914)
- remove dedicated Jaeger port (now that we have it muxed on 8200)
- align standalone config defaults with integration package
- switch `apm-server.sampling.keep_unsampled` default to false
- switch `@timestamp` to date_nanos (maybe add `timestamp.us` runtime field for backwards compatibility)
- replace `<event>.duration.us` with `event.duration` (maybe add runtime fields for backwards compatibility)

**Comment by axw** [comment]
Another thing just popped up while I was looking into our dependence on "classic indices": the original source mapping storage implementation. APM Server indexes and searches sourcemaps in `apm-<version>-sourcemap`.

Users can now upload sourcemaps to Kibana, but currently the only way APM Server can receive them is through Fleet. If we are going to maintain support for sourcemapping in standalone APM Server, we will need to have APM Server query Kibana for sourcemaps when running with data streams enabled.

**Comment by axw** [comment]
Remove `apm-server.instrumentation.*` config -- replaced by `instrumentation.*` many releases ago.

**Comment by simitt** [comment]
closing this issue as we created tracking issues and labeled them 8.0 for everything we plan to implement.
