### ISSUE TITLE
Improve healthcheck endpoint

### ISSUE THREAD

**Issue by jalvz** [elastic/apm-server#2632]
This is a meta-issue to capture requests to improve the healthcheck endpoint:

- [ ] Show health of the configured output elastic/apm-server#1366
- [ ] Return something when there is no secret token elastic/apm-server#1828 
- [ ] Add "apm-server" to a component property elastic/apm-server#2538 
- [ ] Expose capabilities elastic/apm-server#2341

**Comment by simitt** [comment]
Closing as all related tasks were closed.
