### ISSUE TITLE
Update Documentation for APM-Server

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#274]
This is a meta issue for collecting documentation related issues that need to be resolved.

* [x] Update Installation Documentation for Windows
* [x] Document the config options (see [beats docs](https://www.elastic.co/guide/en/beats/libbeat/6.1/config-file-format.html)) #548 
* [x] [Specifying ES output](https://www.elastic.co/guide/en/beats/filebeat/current/elasticsearch-output.html) #548 
  * [x] [Configuring SSL](https://www.elastic.co/guide/en/beats/filebeat/current/configuration-ssl.html) (for the output) #548 
* [x] [Setting up the Kibana endpoint](https://www.elastic.co/guide/en/beats/filebeat/current/setup-kibana-endpoint.html) (see also: https://github.com/elastic/apm-server/issues/476) #548 
* [x] [Using env vars in config](https://www.elastic.co/guide/en/beats/filebeat/current/using-environ-vars.html) (see also https://github.com/elastic/apm-server/issues/440) #548 
* [x] [Setting up logging](https://www.elastic.co/guide/en/beats/filebeat/current/configuration-logging.html) https://github.com/elastic/apm-server/issues/542 @roncohen
* [x] [Troubleshooting](https://www.elastic.co/guide/en/beats/filebeat/current/troubleshooting.html) https://github.com/elastic/apm-server/pull/551 @simitt
  * [Get help](https://www.elastic.co/guide/en/beats/filebeat/current/getting-help.html)
  * [Enable debugging](https://www.elastic.co/guide/en/beats/filebeat/current/enable-filebeat-debugging.html)
* [x] Document enabling frontend endpoint https://github.com/elastic/apm-server/issues/468 @simitt
* [x] Add description of trace/transaction/span https://github.com/elastic/apm-server/issues/297 @simitt
* [x] Add x-pack security configuration (see [beats docs](https://www.elastic.co/guide/en/beats/auditbeat/6.0/beats-user-access.html)) #545 @graphaelli

**Comment by roncohen** [comment]
Updated with a bunch of additional documentation we're still lacking
