### ISSUE TITLE
[Jaeger] Support receiving Jaeger spans

### ISSUE THREAD

**Issue by axw** [elastic/apm-server#2886]
We have heard from users that they would like to use their existing Jaeger instrumentation with Elastic APM. It is already possible to store and search span data in Elasticsearch, but what is missing is integration with Elastic APM and related features, such as visualisation in the APM UI, central configuration, log correlation.

There are at least a couple of ways we can go about this:
- We already have an issue to implement an OpenTelemetry Exporter (https://github.com/elastic/apm/issues/98). We could wait for OpenTelemetry Collector to be ready, and require users to redirect their Jaeger agents to OpenTelemetry Collector.
- We could add support to the APM Server to ingest Jaeger data directly.

The exporter option has a couple of problems. First and foremost, it's more complex: an additional component is required, complicating users' lives. Second, we would not be able to support Jaeger's remote sampling in this way.

I suggest that we add support directly to the APM Server for receiving spans, and translating them into our data schema. The server would effectively be a drop-in for jaeger-collector. To do this, we'll need to introduce HTTP and gRPC endpoints, for receiving spans directly from clients, and from jaeger-agent, respectively. Jaeger also supports TChannel, but I don't think we need to support this.

It may be useful to reuse some of the machinery inside [opentelemetry-collector](https://github.com/open-telemetry/opentelemetry-collector), so that the server is effectively implementing an OpenTelemetry Exporter within the same process. This may enable us to add support for additional trace data sources in the future. I have prototyped this approach here: https://github.com/elastic/apm-server/compare/7.x...axw:otel-7.x (sorry, it's a bit of a mess.)

One thing that is yet to be solved is auth. A limited subset of the Jaeger clients (Java and C#) support the `JAEGER_AUTH_TOKEN` config, which can be used to send a bearer token along with requests to the collector. This only works when using HTTP. The Jaeger agent only supports client certificate auth. We do support this, but it might also be worth a lighter-weight option, such as ferrying a secret/bearer token through tags, using the `--jaeger.tags` CLI flag.

**Comment by simitt** [comment]
TODOs:
* [ ] Finish adding gRPC endpoint, running on port 14250, to ingest spans sent by jaeger-agent in model.proto format
* [ ] Finish adding HTTP endpoint, running on port 14268, to ingest spans sent by jaeger-clietn via thrift over http
* [ ] Investigate if healthcheck endpoint on port 14269 is needed and implement if so
* [ ] Finish implementation for transformation of jaeger events to Elastic APM events. Validate input and decide on a strategy for invalid input: figure out which attributes are required for UI and how to fill them if missing, or log event and drop it
* [ ] When using probabilistic sampling jaeger only sends sampled spans. Elastic APM requires a 100% of the transaction events and only samples spans. Investigate how to solve sampling with jaeger integration.
* [ ] auth handling: Add integration tests for client auth via TLS
* [ ] auth handling: Investigate further options, e.g. using special tags
* [ ] Check out error responses expected by jaeger
* [ ] Figure out how to and to which extent to add system tests in the APM Server (maybe the [hotrod example app](https://github.com/jaegertracing/jaeger/tree/master/examples/hotrod) can be leveraged)
* [ ] Add dockerized setup for automated tests in the integration repo: have a dedicated test app using the jaeger agent for instrumentation and expecting events in ES in a certain format


Out of scope:
* support for tchannel
* providing endpoint exposing metrics
* support on ESS

**Comment by axw** [comment]
>  [concept]: When using probabilistic sampling jaeger only sends sampled spans. Elastic APM requires a 100% of the transaction events and only samples spans. Investigate how to solve sampling with jaeger integration.

Outside of the context of Jaeger, there's been some discussion around relying on metrics so we don't need to send and store non-sampled transactions. This is https://github.com/elastic/apm/issues/104.

If we were to do that, we could have the server aggregate metrics based on sampled Jaeger trace data. Jaeger sends up the sampling rate in effect at the time a trace is captured, so we can scale the count/total based on that.

**Comment by simitt** [comment]
Work for 7.6 release has been finished. Moving follow up topics to new meta issue https://github.com/elastic/apm-server/issues/3340.
