### ISSUE TITLE
Feature: tail-based sampling

### ISSUE THREAD

**Issue by axw** [elastic/apm-server#4185]
Add support to for tail-based sampling: sampling based on properties of the trace known only after the trace completes, such as the root transaction duration and outcome. This will enable users to retain traces based on how interesting they are, i.e. preferring to keep slower traces, or traces with a failure outcome.

The solution we plan to implement will be primarily based in apm-server, in order to avoid network transfer costs and adding significant load on Elasticsearch. Servers will individually reservoir-sample root transactions, and synchronise their sampling decisions in order to index any other events that are part of sampled traces.

- [x] implement local event storage elastic/apm-server#4108
- [x] implement publish/subscribe for synchronising sampled trace IDs elastic/apm-server#4139
- [x] implement reservoir sampling elastic/apm-server#4182
- [x] implement dynamic trace group sampling policies (sample trace group X with percentage Y, ...) elastic/apm-server#4320
- [ ] implement an efficient codec for storing events elastic/apm-server#4120
- [x] monitoring, logging #4346 
- [x] telemetry https://github.com/elastic/apm-server/pull/4360
- [ ] documentation

**Comment by axw** [comment]
Closing this meta issue, issues for remaining things have been opened and can be tracked independently.
