### ISSUE TITLE
Follow up issue for TLS implementation

### ISSUE THREAD

**Issue by ruflin** [elastic/apm-server#44]
In https://github.com/elastic/apm-server/pull/32 TLS was implemented. This is a follow up issue to track some additional changes which should be investigated or made:

* [ ] Add system tests for tls usage to make sure config behaviour is as expected
* [ ] Clean up go imports: https://github.com/elastic/apm-server/pull/32/files#diff-d5666a18e51cbff4c4f482faa6f9f449R5
* [ ] Investigate reusage of libbeat TLS features: https://github.com/elastic/apm-server/pull/32#discussion_r132541877
* [ ] Use ucfg for `Enabled()` flag
* [ ] Evaluate to use libbeat cert generation: https://github.com/elastic/apm-server/pull/32#discussion_r132553716
* [ ] Evaluate to reuse load certificate from libbeat: https://github.com/elastic/beats/blob/c821b84cf55f88778c9702a60aea52c52d5643d7/libbeat/outputs/tls.go#L150

**Comment by sterchelen** [comment]
Hi @ruflin , I'm looking to contribute to this project...
For the following point:
>  Use ucfg for Enabled() flag
What did you meant ? Replacing the `isEnabled()` function by using the ucfg package ?

**Comment by ruflin** [comment]
@sterchelen Happy to hear you want to contribute.

For the `Enabled()` part: It is exactly as you described to replace `isEnabled` by the internal `Enabled()` function from go-ucfg. But I think I tried to this quickly in the past and it actually made the code more complex instead of simpler and is the reason we went with the implementation we have now. 

In general it would be great to share code between libbeat and apm-server for TLS (if possible) but never checked in detail how much we can share.

**Comment by sterchelen** [comment]
I can see if it's possible to share the TLS usage of beats with the apm-server.

@ruflin , sorry to ask a question of this type here but do you have a slack channel or anything else to talk more freely with the rest of the team ? I didn't see a link to a chat room on the contributing page...

Thank you.

**Comment by ruflin** [comment]
@sterchelen Our main communication channel is Github. Most teams also have an IRC channel: https://www.elastic.co/community But APM does not have one yet.

**Comment by watson** [comment]
@sterchelen we also have our Discuss forums: https://discuss.elastic.co/c/apm
@ruflin Inspired by your comment, I took the liberty to create the channel #elastic-apm on Freenode. I'm a rebel, sorry 😅

**Comment by sterchelen** [comment]
@ruflin I made an investigation to reuse the `loadCertificate` function in libbeat. Here is my point of view:

- We could use the `CertificateConfig` type https://github.com/elastic/beats/blob/c821b84cf55f88778c9702a60aea52c52d5643d7/libbeat/outputs/tls.go#L41. Only this type, for the moment, because we didn't have yet the others TLS features implemented (based on this comment --> https://github.com/elastic/apm-server/pull/32#discussion_r132541877)
- Create our own `loadCertificate` function. We shall, also, extract the `readPEMFile` function which is the central point to decrypt a `pem` file based on a passphrase.
- Finally, on the `run` function https://github.com/elastic/apm-server/blob/master/beater/server.go#L70, based on the `isEnabled()` test we load the `tls.Config` and affect it to the `http.Server`. The `tls.Config` contains the certificate.

With this feature we can handle a certificate that is protected by a passphrase. It could, also, allows to start the "refactoring" of the TLS usage and reuse more or less the libbeat version.

I can start working on it...

**Comment by ruflin** [comment]
@sterchelen I like the idea. How would the config look like after this change? Could you post a yaml example?

I would like to get @jalvz opinion here before we start working on it has he did the implementation and knows best if this fits in.

**Comment by sterchelen** [comment]
@ruflin , here is the yaml example:

```yaml
apm-server:

  host: "localhost:8200"
  read_timeout: 2s
  write_timeout: 2s
  shutdown_timeout: 5s
  concurrent_requests: 20

  tls.enabled: true
  tls.certificate: "/path/to/cert"
  tls.key: "path/to/private_key"
  tls.key_passphrase: "blabla"
```

`ssl` is the predecessor of `tls` so if we want to be etymologically correct we should use `tls` instead of `ssl`. 
The other modification is the addition of the `tls.key_passphrase`.

**Comment by ruflin** [comment]
The config looks good to. Even though `tls` is more correct, we use `ssl` to be in sync with the rest of the elastic stack so I would keep `ssl` for now.

I want @jalvz to chime in here to see if we are on the right track.

**Comment by sterchelen** [comment]
All right ! Waiting @jalvz thoughts.

**Comment by jalvz** [comment]
sorry, this slipped through the cracks, but overall SGTM

if we are going to duplicate too much code from `loadCertifcate` / `readPEMFile` i think it would be better to expose those functions in libbeat, or at least extract and expose the common bits we need

looking forward to it

**Comment by sterchelen** [comment]
@jalvz Ok, when you say:
> expose those functions in libbeat

You are meaning modifying `libbeat` functions inside the vendor folder ? Or creating a pull request to the [beats](https://github.com/elastic/beats) repository ?

**Comment by jalvz** [comment]
The right way would be a PR in beats, yes.

**Comment by sterchelen** [comment]
As you want... I can create a pull request about this subject.

**Comment by sterchelen** [comment]
PR created --> https://github.com/elastic/beats/pull/5388

**Comment by sterchelen** [comment]
Hi, the PR has been merged ! 

Start working on loading certificate from the libbeat outputs package.

**Comment by jalvz** [comment]
great! 👍

**Comment by sterchelen** [comment]
- Evaluate to use libbeat cert generation --> **Done**
- Evaluate to reuse load certificate from libbeat --> **Done**

**Comment by graphaelli** [comment]
reviewing this for possible inclusion in 6.2 - #235

**Comment by jalvz** [comment]
i'm closing this until a requirement for more functionality comes up. PR235 is still open and can be merged when ready.
