### ISSUE TITLE
[meta] APM Server managed by Elastic Agent with Fleet (GA)

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#4636]
This meta issue collects work required to make APM Server managed by Elastic Agent with Fleet generally available. 

### >= 8.0 
- [x] Create data stream specific pipelines https://github.com/elastic/apm-server/issues/6001
- [x] Ensure APM Server has enough privileges for tail based sampling https://github.com/elastic/apm-server/issues/5490
- [ ] ~Drop privileges when managed by Elastic Agent https://github.com/elastic/apm-server/issues/4571~ Moved to after GA.
- [x] Configurable throughput settings https://github.com/elastic/beats/issues/26638
- [ ] ~Investigate support for spooling to disk https://github.com/elastic/apm-server/issues/5441~ Not that high priority given the new APM output handling
- [x] Java agent auto-attachment  https://github.com/elastic/apm-server/issues/4830 (work on APM Server side is done)

### 7.16 
- [x] Add `message` field to error docs https://github.com/elastic/apm-server/issues/5971
- [ ] ~[stretch goal] Java agent auto-attachment  https://github.com/elastic/apm-server/issues/4830~
- [x] Make use of component templates in APM and restrict dynamic indexing https://github.com/elastic/apm-server/issues/5707
- [x] Align package version with Stack version https://github.com/elastic/apm-server/issues/4898

###  7.15
- [x] Reload configs without restart https://github.com/elastic/apm-server/issues/5039

#### Stretch
- [x] Supporte multiple fleet-server addresses https://github.com/elastic/apm-server/issues/5514
###  7.14
- [x] Meta issue collecting required steps for `7.14` https://github.com/elastic/apm-server/issues/5388

### Kibana - Stack Monitoring
- [x] Same level of insights needs to be provided to users https://github.com/elastic/kibana/issues/90157
- [x] changes in Elastic Agent to expose metrics

###  7.12
- [x] [Meta issue collecting required steps for `7.12`](https://github.com/elastic/apm-server/issues/4558).

**Comment by simitt** [comment]
Closing this as all the required work on the APM Server side for going GA and upgrading to 8.0 has been done. Single bugs (e.g. stack monitoring issues) are tracked separately.
