### ISSUE TITLE
[meta] [fleet] Java agent auto attaching

### ISSUE THREAD

**Issue by jalvz** [elastic/apm-server#4830]
The goal is to enable users to instrument their Java applications with zero configuration.

This requires a few steps:

- [x]  Bundle the Java agent attacher in apm-server (https://github.com/elastic/apm-server/issues/4824)
- [x] Add settings in the fleet policy editor for the attached
  - [x] https://github.com/elastic/observability-design/issues/77
  - [x] https://github.com/elastic/kibana/issues/108513
- [x] Support java attacher settings via apm-server.yml  (https://github.com/elastic/apm-server/issues/4829)
- [x] Support `--download-agent-version` option https://github.com/elastic/apm-server/issues/5853
- [x] ~Download the appropriate version of the Java agent.~ APM Server asks the Elastic Agent to download the Java Agent binaries in a specific version (the version from the apm-server.yml). Elastic Agent downloads the binaries and returns the path to the binaries to the APM Server. (https://github.com/elastic/apm-server/issues/5477)
- [x] APM Server runs the improved Java agent attacher (prefer `$JAVA_HOME/bin/java` over `java`), which takes care of attaching the binary to all matching JVMs on the same host  (https://github.com/elastic/apm-server/issues/5478)
- [x] Process attacher logs (as part of https://github.com/elastic/apm-server/issues/5478)
- [x] limit Java agent auto attachment to not be available when running in ECE/ESS environments (https://github.com/elastic/apm-server/issues/5479)

**Comment by felixbarny** [comment]
Some additional steps:

- Handling of version updates
  - Download new version
  - Stop attacher
  - Start attacher with path to updated `--agent-jar`
  - Delete old agent jar?
- Handling of config changes (ex include/exclude rules)
  - Stop attacher
  - Restart with new config

**Comment by simitt** [comment]
@felixbarny could you help us define more details for this so we can start working on it?

**Comment by jalvz** [comment]
@simitt we should add this to https://github.com/elastic/apm-server/issues/5388, right?

**Comment by simitt** [comment]
good catch @jalvz , added it.

**Comment by jalvz** [comment]
@felixbarny how should we handle java logs in the end? 
will apm-server just log them as if it were their own? should we handle them separately and have extra settings for it (including rotation / etc)?

**Comment by simitt** [comment]
@felixbarny related to https://github.com/elastic/apm-server/issues/4830#issuecomment-784164800 - does that mean that the java agent attacher should not be packaged with the apm-server but that the apm-server needs to check for the latest attacher version and then download that?

**Comment by felixbarny** [comment]
> how should we handle java logs in the end?

My first idea was that APM Server would just forward the standard out from the attacher to it's own log file. But I'm not sure if that's feasible with the logging framework that APM Server uses. It might be tricky to use the same file lock as the underlying log framework to avoid server and attacher logs to be interleaved.

In that case, it's probably best to have a separate log file for the attacher. See the [`--log-file` and `--log-level` options](https://www.elastic.co/guide/en/apm/agent/java/current/setup-attach-cli.html#setup-attach-cli-usage-options) of the attacher on how to do that.

Probably not the best alternative but another option would be to write the std. out of the attacher into it's own log file and APM Server would handle the log file rotation itself.

> does that mean that the java agent attacher should not be packaged with the apm-server

No. The attacher version should always be a fixed one for an APM Server version.

There are two components that are involved. The attacher ([`apm-agent-attach-cli-slim.jar`](https://search.maven.org/search?q=g:co.elastic.apm%20AND%20a:apm-agent-attach-cli)), and the Java agent binaries ([`elastic-apm-agent.jar`](https://search.maven.org/search?q=g:co.elastic.apm%20AND%20a:elastic-apm-agent)).

The APM Server should bundle the attacher. The Java agent binaries are resolved using a different mechanism. It's not 100% clear what that mechanism is. Maybe we'll build those capabilities into the attacher for now and switch to Fleet packages later.

**Comment by stuartnelson3** [comment]
Looking at these two issues:
- https://github.com/elastic/apm-server/issues/5853
- https://github.com/elastic/apm-server/issues/5477

Do we want both of these? It seems like we would be fine doing one of the other -- either apm-server requests the binary download from agent, or the attacher handles it on its own.

Since this behavior is already available in the attacher, it seems like that might be the simpler way to go?

**Comment by axw** [comment]
I see Felix closed the Elastic Agent method issue. Going with #5853 SGTM too. We may want to revise this later to support airgapped environments, but we don't need to worry about that just now.

**Comment by felixbarny** [comment]
The Fleet/Agent Team wasn’t keen on exposing an API to APM Server to
explicitly download a binary. They want Agent to handle dependency
management. The long term plan is to have subpackages but that’ll take a
while.
For the experimental version works via maven central.

**Comment by simitt** [comment]
@stuartnelson3 it looks like all the checkboxes can be ticked, can this be closed?

**Comment by stuartnelson3** [comment]
yep!
