### ISSUE TITLE
[meta] Elastic Agent APM Integration with Fleet [7.14]

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#5388]
This meta issue collects work required to make APM Server managed by Elastic Agent with Fleet for 7.14. This includes work for on-prem and ESS/ECE.

### APM Server
- [x] Support relevant APM Server settings in the UI https://github.com/elastic/apm-server/issues/4528
- [x] Introduce direct agent configuration https://github.com/elastic/apm-server/issues/5018
- [x] Store routable URL https://github.com/elastic/apm-server/issues/4895
- [x] Fetch source maps from Fleet Server https://github.com/elastic/apm-server/issues/5002
- [x] [cloud] Send APM Server configurations to Kibana APM endpoint on startup https://github.com/elastic/apm-server/issues/5377
- [x] [cloud] Hardcode sizing dependent settings in APM Server https://github.com/elastic/apm-server/issues/5372
- [x] Support customization of throughput relevant settings in APM integration https://github.com/elastic/apm-server/issues/5387
~- [ ] Preliminary work for Java agent auto-attaching https://github.com/elastic/apm-server/issues/4830~ continued in 7.15

### Others
- [x] [apm] Inject agent config directly into Fleet policies https://github.com/elastic/kibana/issues/95501
- [x] [apm] User flow to switch from Classic APM indices to Data streams https://github.com/elastic/kibana/issues/100657
- [x] [apm] Onboarding guide
   - [x] [apm] Integrate APM Server configuration with the APM UI https://github.com/elastic/kibana/issues/88659
   - [x] [apm] Add secret_token to agent instructions in legacy Getting Started guide https://github.com/elastic/kibana/issues/100661
   - [x] [apm] Ensure "Check APM Server status" works with fleet https://github.com/elastic/kibana/issues/100672
- [x] [apm] Source map upload endpoint https://github.com/elastic/kibana/issues/95393
- [ ] [apm] Add support for data streams https://github.com/elastic/kibana/issues/94702
- [x] [fleet] Support composable templates https://github.com/elastic/kibana/issues/90454
- [x] [apm] Design for policy configuration editor https://github.com/elastic/observability-design/issues/29 
- [ ] [fleet] Allow to customize pipelines per data stream https://github.com/elastic/package-spec/issues/129, or at a minimum provide docs on how to customize (draft docs PR https://github.com/elastic/beats/pull/23247)
- [ ] [fleet] Support custom ILM policies per data stream https://github.com/elastic/package-spec/issues/128
- [ ] changes in ESS/ECE
