### ISSUE TITLE
[cloud] Provide upgrade experience from 7.16 to 8.0

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#6235]
This is work where we need to keep track of, but won't be done in the apm-server:

* [x] newly created apm deployments >= 8.0 are running a managed apm-server
* [x] existing deployments with a standalone apm-server register a deprecation warning in the Upgrade Assistant (https://github.com/elastic/kibana/issues/113088)
  * [ ] Upgrade Assistant should support links in the manual instruction steps (https://github.com/elastic/kibana/issues/111068)
  * [ ] Upgrade Assistant should label apm deprecations with a specific batch (https://github.com/elastic/kibana/issues/112985)
* [ ] cloud API deprecates `apm` resource (code, documentation) for deployments >= 8.0
* [x] cloud API introduces new resource
* [x] APM UI switch to managed mode should revise naming (classic indices to data streams, vs. standalone to managed apm-server) (https://github.com/elastic/kibana/issues/112994)
* [ ] ~Show deprecation note in APM UI when running a standalone apm-server (https://github.com/elastic/kibana/issues/120108)~ moved to 8.1

**Comment by stuartnelson3** [comment]
issue tracked elsewhere
