### ISSUE TITLE
Tail Based Sampling GA 

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#6894]
This is a task list of necessary work for declaring tail based sampling GA. It is a follow up of https://github.com/elastic/apm-server/issues/5484, where some preliminary testing was done to identify the current status.

## Required Feature Work

* [x] https://github.com/elastic/apm-server/issues/5125
* [x] https://github.com/elastic/apm-server/issues/5490
* [ ] #4586 
* ~[ ] #4120~ Moved out of the QA requirements
* [x] Support TBS configuration options
  * [x] #6895
  * [x] https://github.com/elastic/kibana/issues/121534
* [x] #5101

## Stretch
* [ ] #4410
* [ ] #7025

## Identified Bugs
* [x] #6581
* [x] #6638 
* [x] #6639 
* [x] #6640 
* [x] #6642

## Test Plan
* [ ] Verify that sampling logic is applied correctly (use at least one service with an actual apm agent)
* [ ] Verify the reservior sampling implementation (mix of slow and fast traces)
* [ ] Check that logs are sufficient and helpful (on error, when reaching max number of dynamic services etc. )
* [ ] Check that metrics are sufficient and helpful
* [ ] Test performance, on a larger scale with multiple indices and shards
* [ ] Follow documentation and verify that it is self-explanatory and sufficient (depends on #4586 )
* [ ] Test behavior on Elastic Cloud

**Comment by simitt** [comment]
Everything required has been implemented in `8.1`. Let's tick the testplan boxes when testing through the feature. Closing the issue, as the work has been done.
