### ISSUE TITLE
Benchmark 2.0 production ready

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#7540]
In https://github.com/elastic/apm-server/issues/7216 @marclop worked on a POC for a new benchmarking tool for APM data ingestion. The POC is leveraging Opbeans services to create apm events, which are recorded into ndjson files by the new Intake Receiver component. The `apmbench` loader reads from the ndjson files and the runner sends the data to an APM Server, while also collecting statistics which are indexed into a dedicated Elasticsearch. Find a more detailed description in https://github.com/elastic/apm-server/issues/7216#issue-1125938474.

After successfully building the POC, all the components should be tight together in a maintainable way.

## Goals
* New Benchmark tooling is wired up to run automated benchmarks on a fixed set of testdata on a regular schedule
* Can be integrated into the teams workflow when building new features or refactoring (ad-hoc and automated benchmarks)
* Can easily be used by agent developers to create a new testdata set for a new agent version for automated benchmarks, and ad-hoc benchmarks.
* Can be used by engineers and developers outside the apm-server team for throughput ananlysis with a targeted throughput per unit. 
* Update the [processing & performance guide](https://www.elastic.co/guide/en/apm/guide/current/processing-and-performance.html) with updated numbers

## Tasks
* [ ] benchmark limits for `events/unit` should be configurable (in addition to currently supported max. load)
* [ ] collect additional metrics for better insights 
* [ ] Implement alternative solution to committing the generated `ndjson` files in the APM Server repo. As one option, we discussed uploading generated files to s3 and providing a small uploader tool that is easy to use. Ideally the tool 
* [ ] Support feature specific use cases, at least, there should be enough data, or data (trace_ids, ..) being manipulated without losing semantic meaning, to test tail based sampling. 
* [ ] https://github.com/elastic/observability-dev/issues/2014
* [ ] build a meaningful dashboard 
* [ ] collaborate with the automation team for plumbing everything together and automatically run the benchmarks on a regular basis
