### ISSUE TITLE
APM Server Soak testing

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#8302]
## Problem

Performance or resource usage issues might only manifest over time. Recently we also experienced a situation where issues became appearant when a high number of apm agents were connecting to one APM Server. 

The APM Server team currently does not maintain a long running setup that would help identify and avoid such issues. We want to improve the understanding of APM Server's limits, and ensuring they do not regress. For example how many concurrent agents can APM Server handle? What throughput can APM Server sustain? Is performance stable over an extended period (e.g. days) of sustained workload?

## Solution

We should have an always-on deployment to which we send a sustained, typical workload, such as described in https://github.com/elastic/apm-server/issues/7858 (we should define a small number of usecases for soak testing). 
We will use platform features for observing APM Server performance and alerting APM Server developers when performance is outside expectations.

We may reuse components developed for benchmarking e.g. reuse automation for creating ESS deployments and "worker nodes" for running the agent workload. Workload may be generated with `apmbench`, using its options to produce a fixed event rate.

### Goals

- We have an always-on deployment on ESS.
- A steady, typical APM agent workload is sent to APM Server.
- APM Server (stack) monitoring is available.
- We can configure and receive alerts in Slack when APM Server memory or CPU usage becomes excessive, or when there is a significant change in throughput, event loss, or HTTP error responses.
- Degradation may occur slowly over time, so alerts must take this into account.

## Non-Goals

It would eventually be useful to extend [apmbench](https://github.com/elastic/apm-server/tree/main/systemtest/cmd/apmbench) to spread load across multiple hosts, with some coordination to gather combined benchmark results. That is out of scope for this issue.
Non-default configuration of APM Server (e.g. enabling tail-based sampling) is out of scope for this issue. 

## Implementation

- [x] #8406
- [x] Deploy a long running APM-Server for the purpose of soak testing
- [x] #8534 
- [x] Create a dashboard for monitoring Soak Test cluster and Load generator status
- [ ] Configure stack monitoring with relevant alerts

## Stretch goals

- [ ] #8448 
- [ ] #8449

**Comment by lahsivjar** [comment]
This is nice. I would propose to introduce Service Level Objectives (SLOs) for monitoring & alerting needs. On a high level, we can do this by introducing Availability and Latency SLOs for ingestion by APM-Server (Clients <> APM-Server requests) and Coverage and Throughput SLI for APM-Server <> ES processing. We can define the SLIs for these SLOs as follows:

1. Availability SLI: The proportion of good requests to total requests as served by
2. Latency SLI: The proportion of requests faster than an agreed upon threshold
3. Coverage SLI: The proportion of data sent to ES successfully
4. Throughput SLI: The proportion of time data sent to ES was faster than an agreed upon rate threshold

With SLIs setup, we can utilise error budgets to objectively look into the reliability of APM-Server as well as setup alerts. Burn rate based alerts will help us capture slow or fast degradation reliably. What are your thoughts on this?

**Comment by axw** [comment]
@lahsivjar I like that sound of that, though it's possibly a bit more involved than what I had in mind originally.

For availability, were you thinking we would monitor it from the client's perspective? Or only from the server's? For the purpose of soak testing, I don't think we care about network/proxy latency, and only APM Server's service time. Similarly, I think if there's some upstream proxy or network connectivity issue then it's not relevant to this exercise, and so for availability we would only care about the success rate of requests that reach APM Server.

**Comment by lahsivjar** [comment]
> For availability, were you thinking we would monitor it from the client's perspective?

I was proposing only monitoring APM-Server. All the metrics we require fro the SLIs can be instrumented on APM-Server if they are not already there (agreed on your point on not considering latency and hops introduced by upstream proxies).

> and so for availability we would only care about the success rate of requests that reach APM Server

Agreed, if a request doesn't reach APM-Server it lies with the client to either retry or discard and I don't think we need to include this in our measurements.

> though it's possibly a bit more involved than what I had in mind originally

I agree, it will increase the scope of this issue. I think having this framework would help us with better reasoning about the performance of the APM-Server and establishing the groundwork for publishing our guarantees as a cloud service.
