### ISSUE TITLE
8.6 Manual Test Plan

### ISSUE THREAD

**Issue by marclop** [elastic/apm-server#9556]
# Manual Test Plan

When picking up a test case, please add your name to this overview beforehand and tick the checkbox when finished.
Testing can be started when the first build candidate (BC) is available in the CFT region.

## Smoke Testing ESS setup

Thanks to https://github.com/elastic/apm-server/issues/8303 further smoke tests are run automatically on ESS now.
**Consider extending the smoke tests to include more test cases which we'd like to cover**

## Go agent

No code changes since `v2.2.0` release.

## Lambda extension

- [ ] https://github.com/elastic/apm-aws-lambda/pull/337
- [ ] https://github.com/elastic/apm-aws-lambda/pull/340
- [ ] https://github.com/elastic/apm-aws-lambda/pull/341 - Optional??

## APM Kubernetes Attacher

No code changes.

## Test cases from the GitHub board

[apm-server 8.6 test-plan](https://github.com/elastic/apm-server/issues?q=is%3Aissue+label%3Atest-plan+-label%3Atest-plan-ok+is%3Aclosed+label%3Av8.6.0)

Add yourself as _assignee_ on the PR before you start testing.

## Regressions

Link any regressions to this issue.
